# Generated by Django 4.0 on 2022-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
