# Generated by Django 4.0 on 2022-05-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_accesstoken_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='file',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
